apiVersion: test-argo/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  sources:
  - repoURL: https://github.com/savenkovv/test-argocd.git
    targetRevision: HEAD
    path: apps/
    directory:
      recurse: true
      include: '**/app.yaml'
      
  syncPolicy:
    automated:
      prune: true
      selfHeal: true